version: "3"
services:
  db:
    image: postgres:11-alpine
    restart: unless-stopped
    volumes:
      - db_vrwiki_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
  wiki:
    depends_on:
      - db
    image: requarks/wiki:2
    environment:
      LETSENCRYPT_DOMAIN: "xrgamedev.com"
      LETSENCRYPT_EMAIL: "skid@skidvis.com"
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASSWORD}"
      DB_NAME: "${DB_DATABASE}"
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3443:3443"
volumes:
  db_vrwiki_data: 
